# Generated by Django 4.2.27 on 2025-12-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True, db_index=True)),
                ('amount', models.FloatField()),
                ('phone', models.CharField(max_length=20)),
                ('reference', models.CharField(max_length=100)),
                ('timestamp', models.CharField(max_length=40)),
            ],
        ),
    ]
