# Generated by Django 4.2.27 on 2025-12-11 22:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mpesatransaction',
            options={'ordering': ['-id'], 'verbose_name': 'M-Pesa Transaction', 'verbose_name_plural': 'M-Pesa Transactions'},
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='checkout_request_id',
            field=models.CharField(blank=True, help_text='STK request ID', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='result_code',
            field=models.CharField(blank=True, help_text='Lipana API result code', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='result_description',
            field=models.TextField(blank=True, help_text='API response description', null=True),
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('timeout', 'Timeout')], db_index=True, default='pending', help_text='Current transaction status', max_length=20),
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Transaction amount in KES', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='phone',
            field=models.CharField(db_index=True, help_text='Customer phone number (254XXXXXXXXX)', max_length=20, validators=[django.core.validators.RegexValidator('^254\\d{9}$', 'Phone must be in format 254XXXXXXXXX')]),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='reference',
            field=models.CharField(db_index=True, help_text='Transaction reference/description', max_length=100),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='timestamp',
            field=models.CharField(help_text='M-Pesa API response timestamp', max_length=40),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='transaction_id',
            field=models.CharField(db_index=True, help_text='Unique Lipana transaction ID', max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='mpesatransaction',
            index=models.Index(fields=['phone', '-id'], name='mpesa_app_m_phone_d0479c_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesatransaction',
            index=models.Index(fields=['status', '-id'], name='mpesa_app_m_status_c54996_idx'),
        ),
    ]
