# Generated by Django 4.2.27 on 2025-12-13 18:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mpesatransaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'M-Pesa Transaction', 'verbose_name_plural': 'M-Pesa Transactions'},
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='result_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
